### PR TITLE
Default view

### PR DESCRIPTION
**Pull request by EvilGuyWhoEatsBrains**
For my project I ran into a situation where I needed to be able to set the default view. But using the "default" data attribute would throw the "You need to create a view" error. 

I changed the code to what I think the original intention was. The code will now first look for a view with the "default" data attribute and if not found will look for the first view. If no views are found, then the "You need to create a view" error will be thrown.

### CODE REVIEW

**Comment by imaffett** [comment]
Heya Pat, it's Bob from the office down the hall. It's good to see you buddy, how've you been?

Thanks for the fix.   That was the intended way for it to work.  I will merge and rebuild the build directory shortly.

**Comment by EvilGuyWhoEatsBrains** [comment]
Wrong Pat, I'm a little further then down the hall from you :)

**Comment by imaffett** [comment]
With your name, how have you not memorized Re: Your Brains  -  https://www.youtube.com/watch?v=S6vnM9I7HIo

**Comment by EvilGuyWhoEatsBrains** [comment]
Apparently I don't crawl out from under my rock very often. How have I not seen that before? lol

**Pull request merged**
