### PR TITLE
"active" class not being removed from panels

### PR DESCRIPTION
**Pull request by patrick-lake**
I ran into a situation where navigating using the anchor or loadContent approaches wasn't showing the correct panel. I noticed that the "active" class wasn't being removed from previous panels that had been viewed which was causing the issue.

I'm not sure this is the best approach, but it was the only solution I could come up with that worked. The removal of the class is in a timer so that the panel doesn't disappear before the transition completes.

### CODE REVIEW

**Comment by imaffett** [comment]
Any chance you can provide a demo showing this?

**Comment by EvilGuyWhoEatsBrains** [comment]
I'll try in the next couple of days.

**Comment by jvence** [comment]
I think this is a major bug that need to be addressed. Not sure using a timer to remove the 'active' class style is the best approach. I've reported the bug with an example at https://github.com/01org/appframework/issues/866

**Comment by imaffett** [comment]
@jvence - Then submit a pull request with a sample that has it fixed.  That "addresses" it :+1:

**Pull request closed without merging**
