### PR TITLE
Enable scroll on swipe elements

### PR DESCRIPTION
**Pull request by langowskiadam**
https://github.com/01org/appframework/issues/869

Example of solve problem from issue above

### CODE REVIEW

**Comment by langowskiadam** [comment]
This merge is missing. Please check, why it's gone.

**Comment by imaffett** [comment]
what merge?

**Comment by langowskiadam** [comment]
Merge from this pull above https://github.com/01org/appframework/pull/879
isn't in source below.
https://github.com/01org/appframework/blob/master/partials/touch.html

It was few days ago and now is missing.

**Comment by imaffett** [comment]
can you create a new PR with the fix for the demo?

**Comment by langowskiadam** [comment]
https://github.com/01org/appframework/pull/883 here is it:)

**Pull request merged**
